name: bedwars
main: br.com.logicmc.bedwars.BWMain
version: 1.0
author: icarus
depend:
  - core
commands:
  tempmute:
  mute:
  lobby:
  party:
  tempo:
  setisland:
  setlobby:
  setarena:
  ping:
  gamemode:
  unban:
  unmute:
  tempban:
  ban:
  ping:
  admin: