name: bedwars
main: br.com.logicmc.bedwars.BWMain
version: 1.0
author: icarus
softdepend:
  - core
commands:
  givebox:
  movearena:
  g:
  tempmute:
  mute:
  lobby:
  party:
  tempo:
  setisland:
  setlobby:
  setarena:
  ping:
  unban:
  unmute:
  tempban:
  ban:
  ping:
  admin:
  kick: